language: python
dist: trusty
sudo: false

python:
  - "3.6"
  - "nightly"

install:
   - ./setup.py develop
   - pip3 install git+git://github.com/PyCQA/pylint.git@79f45263a8904533160d3fa0d4e69b11d3d7d315
   - pip3 install git+git://github.com/PyCQA/astroid.git@12b673267dce7c899ca384792386ed9b657fe66a

script:
  - pytest --verbose --tb=native
  - pylint asks tests/*.py

notifications:
  email:
    on_success: change
    on_failure: change
  irc:
    channels:
      - "irc.freenode.net#8banana"
    skip_join: true
    on_success: change
    on_failure: always
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} %{build_url}"
